version: "3"
services:
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
      - "8480:8480"
    environment:
      - KEYSTORE_SECRET
      - KC_ADMIN_USERNAME 
      - KC_ADMIN_PASSWORD
      - KC_LOG_LEVEL
      - DATABASE_URL
      - PORT
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_USER 
    volumes:
      - ./dbdata:/var/lib/postgresql/data